<a href="https://colab.research.google.com/github/daonly/2023Autumn/blob/main/23_2_%EB%8D%B0%EC%9D%B4%ED%84%B0%EA%B3%BC%ED%95%99%EC%9D%84%EC%9C%84%ED%95%9C%EC%88%98%ED%95%99%EA%B3%BC%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D_%EC%8B%A4%EC%8A%B5_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 데이터과학을위한수학과프로그래밍 실습 4차시

## Numpy 간략한 소개

- `NumPy`는 다차원 array에 대한 저장 및 수학적 연산을 지원합니다.
- `NumPy`는 내부적으로 C로 작성되어 빠릅니다.
- `NumPy`는 CPU, GPU 등 다양한 하드웨어를 지원합니다.
- `NumPy`는 `Pandas`, `matplotlib`, `statmodels` 등 데이터 과학 패키지와 유연하게 연결됩니다.

## Size of array

In [1]:
import numpy as np

In [8]:
data = np.array([[1, 2],
                 [3, 4],
                 [5, 6]], dtype=float)

In [3]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

`np.array`의 크기에 대한 정보는 다음과 같이 확인할 수 있습니다.

In [4]:
data.ndim

2

In [5]:
data.size

6

In [6]:
data.shape

(3, 2)

In [9]:
data.dtype  #data가 클 때는 float32를 쓰는 것도 ㅊㅊ

dtype('float64')

In [10]:
data.T

array([[1., 3., 5.],
       [2., 4., 6.]])

<img src=https://numpy.org/doc/stable/_images/np_matrix_indexing.png>

## Slicing, Indexing

`np.array`에 대한 슬라이싱을 연습해보겠습니다.

In [11]:
data[0,1]

2.0

In [12]:
data[1:2]

array([[3., 4.]])

In [13]:
data[1:2, :]

array([[3., 4.]])

In [14]:
data[0:2, 0]

array([1., 3.])

In [15]:
data > 3

array([[False, False],
       [False,  True],
       [ True,  True]])

In [18]:
data[data > 3]=3

In [19]:
data

array([[1., 2.],
       [3., 3.],
       [3., 3.]])

## Array Operations

array를 생성하고, 해당 객체의 정보를 확인하고, array에서 원소를 슬라이싱하는 것을 알게 되었습니다. 이제 다른 행렬을 정의한 후, 두 행렬 간의 연산을 수행하겠습니다.

In [25]:
A = np.array([[1,2],
              [2,1]])

In [23]:
B = np.array([[1,0],
              [0,1]])

#### 참고

`np.array`를 만드는 함수는 다양합니다. 그 일부로,

- `np.zeros`
- `np.ones`
- `np.empty`
- `np.eye`

In [20]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [26]:
A + B

array([[2, 2],
       [2, 2]])

In [27]:
A * B

array([[1, 0],
       [0, 1]])

In [28]:
k = 2
k * A

array([[2, 4],
       [4, 2]])

In [29]:
np.dot(A, B)  #identity를 곱했으므로 동일한 결과

array([[1, 2],
       [2, 1]])

In [30]:
np.matmul(A, B)

array([[1, 2],
       [2, 1]])

In [31]:
A @ B #얘가 mp.matmul의 약자

array([[1, 2],
       [2, 1]])

`np.dot`은 input array들이 모두 1-Dimension 일 때, inner product(내적)를 수행합니다.

In [32]:
np.inner(A, B)

array([[1, 2],
       [2, 1]])

In [34]:
np.dot(2, A)

array([[2, 4],
       [4, 2]])

In [35]:
np.matmul(2, A)

ValueError: ignored

``matmul`` differs from ``dot`` in two important ways:

- Multiplication by scalars is not allowed, use ``*`` instead.
- Stacks of matrices are broadcast together as if the matrices
  were elements, respecting the signature ``(n,k),(k,m)->(n,m)``:

```{python}
  >>> a = np.ones([9, 5, 7, 4])
  >>> c = np.ones([9, 5, 4, 3])
  >>> np.dot(a, c).shape
  (9, 5, 7, 9, 5, 3)
  >>> np.matmul(a, c).shape
  (9, 5, 7, 3)
  >>> # n is 7, k is 4, m is 3
 ```

In [ ]:
import numpy as np

# Example with 3-D arrays
tensor1 = np.random.rand(3, 4, 2)  # A 3x4x2 tensor
tensor2 = np.random.rand(3, 2, 5)  # A 3x2x5 tensor

# Using np.dot()
result_dot = np.dot(tensor1, tensor2)

# Using np.matmul()
result_matmul = np.matmul(tensor1, tensor2)

print("Shape of Result (np.dot()):", result_dot.shape)
print("Shape of Result (np.matmul()):", result_matmul.shape)


- If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
  sum product over the last axis of `a` and the second-to-last axis of
  `b`::
  
```python
    dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
```

In [ ]:
i = np.shape(tensor1)[0]
j = np.shape(tensor1)[1]
k = np.shape(tensor2)[0]
m = np.shape(tensor2)[1]

In [ ]:
A = np.zeros((i,j,k,m))

In [ ]:
for i in range(np.shape(tensor1)[0]):
    for j in range(np.shape(tensor1)[1]):
        for k in range(np.shape(tensor2)[0]):
            for m in range(np.shape(tensor2)[1]):
                A[i,j,k,m] = sum(tensor1[i,j,:] * tensor2[k,:,m])

In [36]:
data

array([[1., 2.],
       [3., 3.],
       [3., 3.]])

In [37]:
data.min()

1.0

In [38]:
data.sum()

15.0

In [39]:
data.max()

3.0

In [40]:
data.min(axis=0)

array([1., 2.])

In [46]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

## Broadcasting

<img src=https://numpy.org/doc/stable/_images/broadcasting_1.png>

In [42]:
a = np.array([1, 2, 3])
b = np.array([2])

In [43]:
a.shape

(3,)

In [44]:
b.shape

(1,)

In [45]:
a * b

array([2, 4, 6])

<img src=https://numpy.org/doc/stable/_images/broadcasting_2.png>

In [47]:
a = np.array([[0,0,0],
              [10,10,10],
              [20,20,20],
              [30,30,30]])

In [49]:
b = np.array([1, 2, 3])

In [50]:
a + b

array([[ 1,  2,  3],
       [11, 12, 22],
       [21, 22, 23],
       [31, 32, 33]])

<img src=https://numpy.org/doc/stable/_images/broadcasting_3.png>

In [51]:
b = np.array([1, 2, 3, 4])

In [52]:
a + b

ValueError: ignored



<img src=https://numpy.org/doc/stable/_images/broadcasting_4.png>

In [61]:
a = np.array([0, 10, 20, 30])

In [66]:
a = a.reshape((4,1))

In [59]:
b = np.array([1, 2, 3])

In [67]:
a + b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [69]:
a[:, np.newaxis] + b

array([[[ 1,  2,  3]],

       [[11, 12, 13]],

       [[21, 22, 23]],

       [[31, 32, 33]]])

## Unique item and counts

In [54]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [55]:
np.unique(a)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [56]:
np.unique(a, return_index=True)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14]))

In [57]:
np.unique(a, return_counts=True)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1]))

## Example

1. 1) 아래 주어진 함수 `mean_squared_error(X, w, y)`을 반복문(loops, list comprehension 등)을 사용하지 않고 완성하시오. 함수는 아래 식을 구현하여 평균 제곱 오차를 반환해야 합니다.

$$\frac{1}{N}\sum_{\mathbf{x}_i \in \mathbf{X}} (\mathbf{x}_i \mathbf{w}^\intercal - y_i)^2$$

1. 2) 완성한 함수를 아래 입력에 실행시켜 결과를 출력하시오.
```
np.array([[-1.0, 1.0, 0], [-2.0, 2.0, 3.0]]), np.array([1, 1, 1]), np.array([1, 2])
```

In [72]:
def mean_squared_error(X, w, y):
  return np.mean((np.dot(X, w) - y)**2)

In [73]:
mean_squared_error(np.array([[-1.0, 1.0, 0], [-2.0, 2.0, 3.0]]), np.array([1, 1, 1]), np.array([1, 2])
)

1.0

2. 정규방정식을 활용해서 회귀방정식의 계수를 적합해보고, `scikit-learn`의 함수와 비교해 봅니다. 정규방정식은 아래와 같습니다 ($\beta$는 회귀계수를 의미함).

$$\beta = (X^T X)^{-1} X^T y$$



In [74]:
from sklearn import datasets

In [75]:
diabetes = datasets.load_diabetes()

In [92]:
X = diabetes['data']
y = diabetes['target']

In [80]:
X[:5].shape

(5, 10)

In [95]:
np.column_stack([np.ones(X.shape[0]), X])

array([[ 1.        ,  0.03807591,  0.05068012, ..., -0.00259226,
         0.01990749, -0.01764613],
       [ 1.        , -0.00188202, -0.04464164, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 1.        ,  0.08529891,  0.05068012, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 1.        ,  0.04170844,  0.05068012, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [ 1.        , -0.04547248, -0.04464164, ...,  0.02655962,
         0.04452873, -0.02593034],
       [ 1.        , -0.04547248, -0.04464164, ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [96]:
beta = np.linalg.inv(X.T @ X) @ X.T @ y

In [94]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X, y)

LinearRegression()

In [103]:
(lr.intercept_ + X @ lr.coef_)[:5]

array([206.11667725,  68.07103297, 176.88279035, 166.91445843,
       128.46225834])

In [99]:
lr.predict(X)[:5]

array([206.11667725,  68.07103297, 176.88279035, 166.91445843,
       128.46225834])

In [102]:
(X @ beta)[:5]

array([ 53.98319308, -84.06245119,  24.74930619,  14.78097427,
       -23.67122583])

## 참고자료

- NumPy: the absolute basics for beginners, https://numpy.org/doc/stable/user/absolute_beginners.html
- [Numpy] 행렬곱 함수 np.matmul 사용법, np.dot과의 차이, https://jimmy-ai.tistory.com/104